name: flutter_85bet_mobile
description: 85Bet mobile app for multi platforms.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.6+2

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.2.4
  flutter_localizations:
    sdk: flutter

  # Firebase analytics
#  firebase_core: ^0.5.3
#  firebase_analytics: ^6.3.0

  # A wrapper around InheritedWidget to make them easier to use and more reusable. https://pub.dev/packages/provider
  provider: ^4.3.3
  # Object Injectors https://pub.dev/packages/get_it
  get_it: ^5.0.4
  # Functional programming thingies https://pub.dev/packages/dartz
  dartz: ^0.9.2
  # MobX https://pub.dev/packages/mobx
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  # Navigator https://pub.dev/packages/auto_route
#  auto_route: ^0.5.0
  # After Layout https://pub.dev/packages/after_layout
  after_layout: ^1.0.7+2
  # Debug Logger https://pub.dev/packages/logger
  logging: ^0.11.4
  # App info
  package_info: ^0.4.3+2
  # Device info
  device_info: ^1.0.0
  # UUID
  uuid: ^2.2.2

  # Network Service
  # HTTP Request - Dio https://pub.dev/packages/dio
  json_annotation: ^3.1.1
  dio: ^3.0.10
  dio_flutter_transformer: ^3.0.2
  # Cookie Manager https://pub.dev/packages/dio_cookie_manager
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.1
  # HTTP Logger https://pub.dev/packages/pretty_dio_logger
  pretty_dio_logger: ^1.1.1
  # Network state
  connectivity: ^2.0.2
  data_connection_checker: ^0.3.4
  # JWT
#  jwt_decoder: ^1.0.3

  # Data
  # Hive (noSQL) https://pub.dev/packages/hive
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  # Get commonly used locations on the filesystem. Supports iOS and Android.
  # https://pub.dev/packages/path_provider
  path_provider: ^1.6.27
  # Freezed (Data class with Json factory, Combine: super_enum, equatable, to_string,...) https://pub.dev/packages/freezed
  freezed_annotation: ^0.12.0
  # Simpler Data class(equatable, to_string, copyWith, hash) https://pub.dev/packages/dataclass
#  dataclass: ^0.3.0+1
  # Enum class with constant data https://pub.dev/packages/vnum
  vnum: ^1.2.6
  # Super Enum (Enum with dynamic data) https://pub.dev/packages/super_enum
  super_enum: ^0.5.0
  # Value equality https://pub.dev/packages/equatable
  equatable: ^1.2.5
  # Dart class to String https://pub.dev/packages/to_string
#  to_string: ^1.2.1

  # Device Related
  # Handle device permission https://pub.dev/packages/permission_handler
  permission_handler: ^5.0.1+1
  # Custom Permission Dialog https://pub.dev/packages/easy_permission_validator
  easy_permission_validator: ^2.0.1
  # Device Orientation https://pub.dev/packages/orientation
  rxdart: ^0.25.0
  orientation: ^1.2.0
  # Sensor Plugin https://pub.dev/packages/aeyrium_sensor
  #  aeyrium_sensor: ^1.0.7

  # UI
  # Official image extension https://pub.dev/packages/extended_image
  extended_image: ^1.5.0
  # Font Awesome from https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: ^8.11.0
  # Official icons https://pub.dev/packages/cupertino_icons
  # Use with the CupertinoIcons class for iOS style icons.
  #  cupertino_icons: ^0.1.3
  # WebView https://pub.dev/packages/webview_flutter
#  webview_flutter: ^1.0.7
  # Powerful Webview https://pub.dev/packages/flutter_inappwebview
  flutter_inappwebview: ^4.0.0+4
  # Toast https://pub.dev/packages/bot_toast
  bot_toast: ^3.0.5
  # Advance Photo Viewer https://pub.dev/packages/carousel_pro
  carousel_pro: ^1.0.0
  # Relative Align Widget https://pub.dev/packages/relative_layout
  relative_layout: ^0.1.0+1
  # HTML as Text https://pub.dev/packages/flutter_html:
#  flutter_html: ^1.0.2
  css_text: ^2.1.0
  # HTML as Widget https://pub.dev/packages/flutter_widget_from_html_core
  flutter_widget_from_html_core: ^0.5.1+4
  # QR Code generator https://pub.dev/packages/qr_flutter
  qr_flutter: ^3.2.0
  # Icon Badge https://pub.dev/packages/badges
  badges: ^1.1.6
  # Configurable Expansion List Tile https://pub.dev/packages/configurable_expansion_tile
  configurable_expansion_tile: ^1.0.0
  # Scroller Load & Refresh https://pub.dev/packages/flutter_easyrefresh
  flutter_easyrefresh: ^2.1.8
  # Official Video Player https://pub.dev/packages/video_player/example
  video_player: ^1.0.1
  # dot border
  dotted_border: ^1.0.7
  # custom round corner border
  custom_rounded_rectangle_border: ^0.0.1
  # Auto Resize Text
  auto_size_text: ^2.1.0

  # Utils
  # Localization & Datetime format
  intl: ^0.16.1
  # Email Validate https://pub.dev/packages/email_validator
  email_validator: ^1.0.6
  # Launch Url https://pub.dev/packages/url_launcher
  url_launcher: ^5.7.10
  # Share Function https://pub.dev/packages/share_extend
  share_extend: ^1.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3
  reflectable: ^2.2.9
  mobx_codegen: ^1.1.2
#  auto_route_generator: ^0.5.0
  json_serializable: ^3.5.1
  freezed: ^0.12.6
#  dataclass_generator: ^0.4.0
  super_enum_generator: ^0.6.0
#  to_string_generator: ^1.2.1
  hive_generator: ^0.8.2
  #  flutter_vector_icons: ^0.2.1
  source_gen:
  build_runner:

#dependency_overrides:
#  flutter_svg: ^0.18.0
#  dartx: ^0.5.0
#  path: ^1.7.0
#  build: ^1.3.0
#  # for hive generator 0.7.1
#  analyzer: ^0.39.2
#  build_resolvers: ^1.3.10

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/images/vip/
    - assets/images/index/
    - assets/images/roller/
    - assets/images/about/
    - config/app_config.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  # FontAwesome https://fontawesome.com/
  # Example: Icon(IconData(0xf834, fontFamily: 'FontAwesome'))
  fonts:
    - family: FontAwesome
      fonts:
        - asset: assets/fonts/fontawesome_webfont.ttf
          weight: 400
    - family: IconMoon
      fonts:
        - asset: assets/fonts/icomoon.ttf
          weight: 400

# Flutter localization tool
flutter_intl:
  enabled: true
