/// Generated by AssetsRefGenerator on 2020/07/31
class Res {
  //  static const String fontawesome_webfont = "assets/fonts/fontawesome_webfont.ttf";
  static const String wallpaper = "assets/images/content_bg.jpg";
  static const String shadow = "assets/images/shadow.png";
  static const String homeBoxUserAreaBg = "assets/images/index_member.jpg";
  static const String iconBarLogo = "assets/images/icon_bar_logo.png";
  static const String iconPending = "assets/images/icon_pending.png";
  static const String iconAbout = "assets/images/icon_about.png";

//  static const String tbico_casino = "assets/images/index/tbico_casino.png";
//  static const String tbico_slot = "assets/images/index/tbico_slot.png";
//  static const String tbico_sport = "assets/images/index/tbico_sport.png";
//  static const String tbico_fish = "assets/images/index/tbico_fish.png";
//  static const String tbico_lottery = "assets/images/index/tbico_lottery.png";
//  static const String tbico_card = "assets/images/index/tbico_card.png";
//  static const String tbico_movie = "assets/images/index/tbico_movie.png";
//  static const String tbico_recommend =
//      "assets/images/index/tbico_recommend.png";
//  static const String tbico_love = "assets/images/index/tbico_love.png";
  static const String tbico_fav = "assets/images/index/tbico_love_dark.png";

  static const String flico_word = "assets/images/flico_word.png";

//  static const String user_vip_0 = "assets/images/vip/user_vip_0.png";
//  static const String user_vip_1 = "assets/images/vip/user_vip_1.png";
//  static const String user_vip_2 = "assets/images/vip/user_vip_2.png";
//  static const String user_vip_3 = "assets/images/vip/user_vip_3.png";
//  static const String user_vip_4 = "assets/images/vip/user_vip_4.png";
//  static const String user_vip_5 = "assets/images/vip/user_vip_5.png";
//  static const String user_vip_6 = "assets/images/vip/user_vip_6.png";

  static const String walletBgIcon = "assets/images/wlpop_titico.png";
  static const String walletBgIconSmall =
      "assets/images/wlpop_titico_small.png";

//  static const String storeProductNewIcon = "assets/images/new_product.png";

  static const String eventMoneyForeground = "assets/images/event_money.png";

  static const String homeMemberAreaIconDeposit =
      "/images/index/idxusico_dsp.png";
  static const String homeMemberAreaIconWithdraw =
      "/images/index/idxusico_cash.png";
  static const String homeMemberAreaIconTransfer =
      "/images/index/idxusico_tsf.png";
  static const String homeMemberAreaIconVip = "/images/index/idxusico_vip.png";

//  static const String roller_title = "assets/images/roller/title.png";
//  static const String roller_top = "assets/images/roller/top_bg.jpg";
//  static const String roller_wheel_8 = "assets/images/roller/wheel8.png";
//  static const String roller_btn_go = "assets/images/roller/go.png";

//  static const String movie_eg_base = "assets/images/movie_eg/";
//  static const String movie_eg_dark_base = "assets/images/movie_eg_dark/";
//  static const String movie_new_base = "assets/images/movie_new/";
//  static const String movie_new_dark_base = "assets/images/movie_new_dark/";
//  static const String movie_category_action_expand =
//      "assets/images/movie_new/expand.png";
//  static const String movie_category_action_fold =
//      "assets/images/movie_new/fold.png";

  static const String certBvi = "assets/images/about/cert_bvi.png";
  static const String certGc = "assets/images/about/cert_gc.png";
  static const String certMga = "assets/images/about/cert_mga.png";
  static const String certPagcor = "assets/images/about/cert_pagcor.png";

  static const String teamsMcu = "assets/images/about/teams_mcu.png";
  static const String teamsFra1 = "assets/images/about/teams_fra1.png";
  static const String teamsFcb = "assets/images/about/teams_fcb.png";
  static const String teamsLcc = "assets/images/about/teams_lcc.png";
  static const String teamsAfa = "assets/images/about/teams_afa.png";
  static const String teamsIta1 = "assets/images/about/teams_ita1.png";
  static const String teamsHbsc = "assets/images/about/teams_hbsc.png";
}
