/// Generated by AssetsRefGenerator on 2020/12/23
class Res {
  static const String icomoon = "assets/fonts/icomoon.ttf";
  static const String event_money = "assets/images/event_money.png";
  static const String flico_word = "assets/images/flico_word.png";
  static const String icon_bar_logo = "assets/images/icon_bar_logo.png";
  static const String icon_pending = "assets/images/icon_pending.png";
  static const String tbico_card = "assets/images/index/tbico_card.png";
  static const String tbico_casino = "assets/images/index/tbico_casino.png";
  static const String tbico_fish = "assets/images/index/tbico_fish.png";
  static const String tbico_lottery = "assets/images/index/tbico_lottery.png";
  static const String tbico_love = "assets/images/index/tbico_love.png";
  static const String tbico_love_dark =
      "assets/images/index/tbico_love_dark.png";
  static const String tbico_movie = "assets/images/index/tbico_movie.png";
  static const String tbico_recommend =
      "assets/images/index/tbico_recommend.png";
  static const String tbico_slot = "assets/images/index/tbico_slot.png";
  static const String tbico_sport = "assets/images/index/tbico_sport.png";
  static const String new_product = "assets/images/new_product.png";
  static const String roller_btn_go = "assets/images/roller/roller_btn_go.png";
  static const String roller_title = "assets/images/roller/roller_title.png";
  static const String roller_top_bg = "assets/images/roller/roller_top_bg.jpg";
  static const String roller_wheel_8 =
      "assets/images/roller/roller_wheel_8.png";
  static const String tab_corner = "assets/images/tab_corner.png";
  static const String user_vip_0 = "assets/images/vip/user_vip_0.png";
  static const String user_vip_1 = "assets/images/vip/user_vip_1.png";
  static const String user_vip_2 = "assets/images/vip/user_vip_2.png";
  static const String user_vip_3 = "assets/images/vip/user_vip_3.png";
  static const String user_vip_4 = "assets/images/vip/user_vip_4.png";
  static const String user_vip_5 = "assets/images/vip/user_vip_5.png";
  static const String user_vip_6 = "assets/images/vip/user_vip_6.png";
  static const String wlpop_titico = "assets/images/wlpop_titico.png";
  static const String wlpop_titico_small =
      "assets/images/wlpop_titico_small.png";
  static const String bg_reg = "assets/video/bg_reg.mp4";
}
